//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hystory
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Player1 { get; set; }
        public string Player2 { get; set; }
        public int KolvoHod { get; set; }
        public int Win { get; set; }
    }
}
